
# Delete the command comment. Ignored when the comment also contains other content
deleteCommand: true

# Close the source issue after moving
closeSourceIssue: true

# Lock the source issue after moving
lockSourceIssue: true

# Mention issue and comment authors
mentionAuthors: true

# Preserve mentions in the issue content
keepContentMentions: true

# Set custom aliases for targets
aliases:
  pug: thecodechef/sublime-pug-extended
