
repository:
  name: sublime-pug-extended
  description: Pug Extended for Sublime Text 3
  private: false
  homepage: https://www.github.com/thecodechef/sublime-pug-extended
  topics: 
    - pug
    - sublime text
    - sublime-text
    - sublime plugin
    - sublime-plugin
    - sublime syntax
    - sublime-syntax
    - package control
    - package-control
  has_issues: true
  has_wiki: false
  has_projects: true
  has_downloads: true
  default_branch:  master
  branches:
    - name: master
      protection:
        required_pull_request_reviews:
          required_approving_review_count: 1
          require_code_owner_reviews: true
        required_status_checks:
          strict: true
        enforce_admins: true
